### ISSUE TITLE
Continuing your work

### ISSUE THREAD

**Issue by ThienNguyen2002** [ThienNguyen2002/ITServerless#85]
Final Project Step 7 ⬤◯◯◯◯◯ | 🕐 Estimated completion: 30 mins

## ✅  Task:
- [ ] Continue working in the `final-project` branch
- [ ] Review all of the issues that are currently open:
    - Close the issues that you have completed
    - Add 3-4 more issues based on the work you plan on doing this week (if they are not already there)
    - Label the issues you want to work on as "Priority"
    - Label the issues that you need your mentor's help with as "mentor" and send them to your mentor to review before your meeting
- [ ] 🚀 Commit any changes to the `final-project` branch, make a pull request, and merge it
